[tool.poetry]
name = "dataconf"
version = "1.0.0"
description = "Configuration by automatic dataclasses parsing (JSON/YAML/HOCON)"
authors = []
license = "Apache2"
readme = "README.md"
repository = "https://github.com/zifeo/dataconf"
include = [
    "dataconf", "pyproject.toml"
]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
]

[tool.poetry.scripts]
dataconf = 'dataconf.cli:run'

[tool.poetry.dependencies]
python = "^3.8"
pyhocon = "^0.3.54"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
flake8 = "^3.7.9"
black = "^19.10b0"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
